version: '2.3'

services:
  postgres:
    image: postgres:12.1-alpine
    container_name: pleroma_postgres
    restart: always
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: mc4Bk3ycucTfRewcgqSU2n6sxAYuZsjw
      POSTGRES_DB: pleroma
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - pleroma-link

  web:
    build:
      context: ./web
    image: pleroma
    container_name: pleroma_web
    hostname: pleroma_web
    restart: always
    networks:
      - pleroma-link
      - planet-link
    volumes:
      - ./data/uploads:/pleroma/uploads
    depends_on:
      - postgres

networks:
  pleroma-link:
    external: false
  planet-link:
    external: true