version: '2.3'

services:
  postgres:
    image: postgres:11.5-alpine
    container_name: pleroma_postgres
    restart: always
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: ***ひみつ***
      POSTGRES_DB: pleroma
    volumes:
      - ./data/postgres/10:/var/lib/postgresql

  web:
    build: .
    image: pleroma
    container_name: pleroma_web
    restart: always
    ports:
      - "127.0.0.1:8084:4000"
    volumes:
      - ./data/uploads:/pleroma/uploads
    depends_on:
      - postgres
